/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDivisiRouteImport } from './routes/_authenticated/divisi'
import { Route as AuthenticatedGaleriRouteImport } from './routes/_authenticated/galeri'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTemplateRouteImport } from './routes/_authenticated/template'
import { Route as AuthenticatedValidasiRouteImport } from './routes/_authenticated/validasi'
import { Route as AuthenticatedLaporanIndexRouteImport } from './routes/_authenticated/laporan/index'
import { Route as AuthenticatedLaporanIdRouteImport } from './routes/_authenticated/laporan/$id'
import { Route as AuthenticatedLaporanBaruRouteImport } from './routes/_authenticated/laporan/baru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDivisiRoute = AuthenticatedDivisiRouteImport.update({
  id: '/divisi',
  path: '/divisi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriRoute = AuthenticatedGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplateRoute = AuthenticatedTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValidasiRoute = AuthenticatedValidasiRouteImport.update({
  id: '/validasi',
  path: '/validasi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanIndexRoute =
  AuthenticatedLaporanIndexRouteImport.update({
    id: '/laporan/',
    path: '/laporan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaporanIdRoute = AuthenticatedLaporanIdRouteImport.update({
  id: '/laporan/$id',
  path: '/laporan/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanBaruRoute =
  AuthenticatedLaporanBaruRouteImport.update({
    id: '/laporan/baru',
    path: '/laporan/baru',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/divisi': typeof AuthenticatedDivisiRoute
  '/galeri': typeof AuthenticatedGaleriRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/template': typeof AuthenticatedTemplateRoute
  '/validasi': typeof AuthenticatedValidasiRoute
  '/laporan/$id': typeof AuthenticatedLaporanIdRoute
  '/laporan/baru': typeof AuthenticatedLaporanBaruRoute
  '/laporan/': typeof AuthenticatedLaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/divisi': typeof AuthenticatedDivisiRoute
  '/galeri': typeof AuthenticatedGaleriRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/template': typeof AuthenticatedTemplateRoute
  '/validasi': typeof AuthenticatedValidasiRoute
  '/laporan/$id': typeof AuthenticatedLaporanIdRoute
  '/laporan/baru': typeof AuthenticatedLaporanBaruRoute
  '/laporan': typeof AuthenticatedLaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/divisi': typeof AuthenticatedDivisiRoute
  '/_authenticated/galeri': typeof AuthenticatedGaleriRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/template': typeof AuthenticatedTemplateRoute
  '/_authenticated/validasi': typeof AuthenticatedValidasiRoute
  '/_authenticated/laporan/$id': typeof AuthenticatedLaporanIdRoute
  '/_authenticated/laporan/baru': typeof AuthenticatedLaporanBaruRoute
  '/_authenticated/laporan/': typeof AuthenticatedLaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/divisi'
    | '/galeri'
    | '/pengguna'
    | '/profil'
    | '/template'
    | '/validasi'
    | '/laporan/$id'
    | '/laporan/baru'
    | '/laporan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/divisi'
    | '/galeri'
    | '/pengguna'
    | '/profil'
    | '/template'
    | '/validasi'
    | '/laporan/$id'
    | '/laporan/baru'
    | '/laporan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/divisi'
    | '/_authenticated/galeri'
    | '/_authenticated/pengguna'
    | '/_authenticated/profil'
    | '/_authenticated/template'
    | '/_authenticated/validasi'
    | '/_authenticated/laporan/$id'
    | '/_authenticated/laporan/baru'
    | '/_authenticated/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/divisi': {
      id: '/_authenticated/divisi'
      path: '/divisi'
      fullPath: '/divisi'
      preLoaderRoute: typeof AuthenticatedDivisiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeri': {
      id: '/_authenticated/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof AuthenticatedGaleriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/template': {
      id: '/_authenticated/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof AuthenticatedTemplateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/validasi': {
      id: '/_authenticated/validasi'
      path: '/validasi'
      fullPath: '/validasi'
      preLoaderRoute: typeof AuthenticatedValidasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan/': {
      id: '/_authenticated/laporan/'
      path: '/laporan'
      fullPath: '/laporan/'
      preLoaderRoute: typeof AuthenticatedLaporanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan/$id': {
      id: '/_authenticated/laporan/$id'
      path: '/laporan/$id'
      fullPath: '/laporan/$id'
      preLoaderRoute: typeof AuthenticatedLaporanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan/baru': {
      id: '/_authenticated/laporan/baru'
      path: '/laporan/baru'
      fullPath: '/laporan/baru'
      preLoaderRoute: typeof AuthenticatedLaporanBaruRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDivisiRoute: typeof AuthenticatedDivisiRoute
  AuthenticatedGaleriRoute: typeof AuthenticatedGaleriRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTemplateRoute: typeof AuthenticatedTemplateRoute
  AuthenticatedValidasiRoute: typeof AuthenticatedValidasiRoute
  AuthenticatedLaporanIdRoute: typeof AuthenticatedLaporanIdRoute
  AuthenticatedLaporanBaruRoute: typeof AuthenticatedLaporanBaruRoute
  AuthenticatedLaporanIndexRoute: typeof AuthenticatedLaporanIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDivisiRoute: AuthenticatedDivisiRoute,
  AuthenticatedGaleriRoute: AuthenticatedGaleriRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTemplateRoute: AuthenticatedTemplateRoute,
  AuthenticatedValidasiRoute: AuthenticatedValidasiRoute,
  AuthenticatedLaporanIdRoute: AuthenticatedLaporanIdRoute,
  AuthenticatedLaporanBaruRoute: AuthenticatedLaporanBaruRoute,
  AuthenticatedLaporanIndexRoute: AuthenticatedLaporanIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
